version: "3"
services:
  proxy:
    image: "mitmproxy/mitmproxy"
    command: mitmweb --web-iface 0.0.0.0
    ports:
      - "8080:8080"
      - "127.0.0.1:8081:8081"
    volumes:
      - "./mitmproxy:/home/mitmproxy/.mitmproxy"
    container_name: proxy
  client:
    build: .
    image: sandboxed_app
    environment:
      PROXY_SERVER: proxy 
      PROXY_PORT: 8080
    privileged: true
    container_name: client
    volumes:
      - "./mitmproxy:/app/mitmproxy"
      - "./application:/app/files"
    ports:
      - "8090:8080"
      - "8091:8443"
